# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)

Rails.application.load_tasks

task :rails_server do
    `bundle exec rails s -p 3000 -b 0.0.0.0`
end

task :jobs_start do
    `bundle exec rake jobs:work`
end

multitask :server => [:rails_server, :jobs_start]