# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Machine.create(protocol: "http", host: "localhost", port: "4963", update_interval: 1, alias: "pc-test-localhost")
Machine.create(protocol: "http", host: "127.0.0.1", port: "4963", update_interval: 5, alias: "pc-test-127.0.0.1")
##
CpuMetric.create(machine_id: 2, cpu: 88)
CpuMetric.create(machine_id: 2, cpu: 6)
CpuMetric.create(machine_id: 1, cpu: 69)
CpuMetric.create(machine_id: 2, cpu: 39.4)
CpuMetric.create(machine_id: 1, cpu: 5.6)
CpuMetric.create(machine_id: 1, cpu: 77)
CpuMetric.create(machine_id: 2, cpu: 54.2)
CpuMetric.create(machine_id: 2, cpu: 65)
CpuMetric.create(machine_id: 2, cpu: 55.7)
CpuMetric.create(machine_id: 2, cpu: 88.7)
CpuMetric.create(machine_id: 1, cpu: 99.5)
CpuMetric.create(machine_id: 2, cpu: 44.1)
CpuMetric.create(machine_id: 2, cpu: 8.8)
CpuMetric.create(machine_id: 1, cpu: 68)
CpuMetric.create(machine_id: 1, cpu: 44.9)
CpuMetric.create(machine_id: 2, cpu: 60.4)
CpuMetric.create(machine_id: 2, cpu: 95.5)
CpuMetric.create(machine_id: 1, cpu: 10)
CpuMetric.create(machine_id: 2, cpu: 54.2)
CpuMetric.create(machine_id: 1, cpu: 66)
CpuMetric.create(machine_id: 1, cpu: 55.7)
CpuMetric.create(machine_id: 1, cpu: 49.5)
CpuMetric.create(machine_id: 1, cpu: 88.1)
CpuMetric.create(machine_id: 2, cpu: 44.2)
##
RamMetric.create(machine_id: 2, ram: 88)
RamMetric.create(machine_id: 2, ram: 6)
RamMetric.create(machine_id: 1, ram: 69)
RamMetric.create(machine_id: 2, ram: 39.4)
RamMetric.create(machine_id: 1, ram: 5.6)
RamMetric.create(machine_id: 1, ram: 77)
RamMetric.create(machine_id: 2, ram: 54.2)
RamMetric.create(machine_id: 2, ram: 65)
RamMetric.create(machine_id: 2, ram: 55.7)
RamMetric.create(machine_id: 2, ram: 88.7)
RamMetric.create(machine_id: 1, ram: 99.5)
RamMetric.create(machine_id: 2, ram: 44.1)
RamMetric.create(machine_id: 2, ram: 8.8)
RamMetric.create(machine_id: 1, ram: 68)
RamMetric.create(machine_id: 1, ram: 44.9)
RamMetric.create(machine_id: 2, ram: 60.4)
RamMetric.create(machine_id: 2, ram: 95.5)
RamMetric.create(machine_id: 1, ram: 10)
RamMetric.create(machine_id: 2, ram: 54.2)
RamMetric.create(machine_id: 1, ram: 66)
RamMetric.create(machine_id: 1, ram: 55.7)
RamMetric.create(machine_id: 1, ram: 49.5)
RamMetric.create(machine_id: 1, ram: 88.1)
RamMetric.create(machine_id: 2, ram: 44.2)
##
StorageMetric.create(machine_id: 2, storage: 88)
StorageMetric.create(machine_id: 2, storage: 6)
StorageMetric.create(machine_id: 1, storage: 69)
StorageMetric.create(machine_id: 2, storage: 39.4)
StorageMetric.create(machine_id: 1, storage: 5.6)
StorageMetric.create(machine_id: 1, storage: 77)
StorageMetric.create(machine_id: 2, storage: 54.2)
StorageMetric.create(machine_id: 2, storage: 65)
StorageMetric.create(machine_id: 2, storage: 55.7)
StorageMetric.create(machine_id: 2, storage: 88.7)
StorageMetric.create(machine_id: 1, storage: 99.5)
StorageMetric.create(machine_id: 2, storage: 44.1)
StorageMetric.create(machine_id: 2, storage: 8.8)
StorageMetric.create(machine_id: 1, storage: 68)
StorageMetric.create(machine_id: 1, storage: 44.9)
StorageMetric.create(machine_id: 2, storage: 60.4)
StorageMetric.create(machine_id: 2, storage: 95.5)
StorageMetric.create(machine_id: 1, storage: 10)
StorageMetric.create(machine_id: 2, storage: 54.2)
StorageMetric.create(machine_id: 1, storage: 66)
StorageMetric.create(machine_id: 1, storage: 55.7)
StorageMetric.create(machine_id: 1, storage: 49.5)
StorageMetric.create(machine_id: 1, storage: 88.1)
StorageMetric.create(machine_id: 2, storage: 44.2)